import * as fs from "fs";
import * as path from "path";
import { CONFIG_FILE_NAME } from "../../templates/init";
import { GetServiceByUuidAndVersion } from "../apis/service";
import { GetApiById } from "../apis/api";
import { ApiDetail } from "../apis/api/types";
import { ApiDraftDetail } from "../apis/api/types";
import { generateTSCode } from "./generator";
import { ApiOption, serviceClassCode } from "../../templates/service-class";
import { formatCodeByPrettier } from "../../utils/utils";
import { requestDemoCode } from "../../templates/request-demo";

const autoGeneratePrefix = `
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck\n
`;

const readConfig = () => {
    if (!fs.existsSync(CONFIG_FILE_NAME)) {
        console.warn("You need to run `cam init` first");
        process.exit(1);
    }
    try {
        const content = fs.readFileSync(CONFIG_FILE_NAME, "utf-8");
        return JSON.parse(content);
    } catch (error) {
        console.warn(
            "Failed to read config file, please delete it and run `cam init` again"
        );
        process.exit(1);
    }
};

// 拉取service信息并存储到cam.config.json
export const storeServiceInfo = async (
    name: string,
    service_uuid: string,
    version: string
) => {
    const config = readConfig();
    // 检查name是否已存在
    if (config.services && config.services[name]) {
        console.warn(`Service name ${name} already exists`);
        process.exit(1);
    }
    // 检查service_uuid是否已存在
    if (
        Object.values(config.services || {}).some((v: any) => {
            const [existingUuid] = v.split("@");
            return existingUuid === service_uuid;
        })
    ) {
        console.warn(
            `Service ${service_uuid} already exists. If you want to update the version, please remove this service first.`
        );
        process.exit(1);
    }

    try {
        const res = await GetServiceByUuidAndVersion(service_uuid, version);
        if (res.status !== 200) {
            console.warn(res.message || "Failed to get service info");
            process.exit(1);
        }
        if (!config.services) {
            config.services = {};
        }
        config.services[name] = `${service_uuid}@${version}`;
        fs.writeFileSync(
            CONFIG_FILE_NAME,
            JSON.stringify(config, null, 2) + "\n"
        );
        console.log(`Service ${name} added successfully`);
        // 拉取api（初次通过cli添加服务时进行拉取）
        await pullAllApisInAllServices();
    } catch (error) {
        console.error(error);
        process.exit(1);
    }
};

// 从cam.config.json中删除service
export const removeService = async (serviceName: string) => {
    const config = readConfig();
    if (!config.services || !config.services[serviceName]) {
        console.warn(`Service name ${serviceName} does not exist`);
        process.exit(1);
    }
    delete config.services[serviceName];
    try {
        fs.writeFileSync(CONFIG_FILE_NAME, JSON.stringify(config, null, 2));
        console.log(`Successfully removed service ${serviceName}`);
        // 拉取api（删除服务时，更新api）
        await pullAllApisInAllServices();
    } catch (error) {
        console.error(`Failed to remove service ${serviceName}:`, error);
        process.exit(1);
    }
};

// 入口：基于cam.config.json中存储的service信息，拉取全部service的全部api
export const pullAllApisInAllServices = async () => {
    const config = readConfig();
    if (!config.services || Object.keys(config.services).length === 0) {
        console.warn(
            "No service has been added yet. Please use 'cam add <name:uuid@version>' to add a service first."
        );
        process.exit(1);
    }
    // 清空cam-auto-generate目录下的所有文件
    const outDir = config.outDir || ".";
    if (fs.existsSync(outDir)) {
        // 递归删除整个目录及其内容
        fs.rmSync(outDir, { recursive: true, force: true });
    }
    // 重新创建一个干净的目录
    fs.mkdirSync(outDir, { recursive: true });

    // 遍历cam.config.json中存储的service信息，拉取全部service的全部api
    for (const [name, UuidAndVersion] of Object.entries(config.services)) {
        const [service_uuid, version] = (UuidAndVersion as string).split("@");
        if (!service_uuid || !version) {
            console.warn(
                `Invalid service info ${UuidAndVersion} for service ${name}. Please use 'cam add <name:uuid@version>' to add instead.`
            );
            continue;
        }

        // 一个service确定一个输出目录
        const outputDir = path.join(outDir || ".", name);
        // 确认输出目录存在
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }
        let namespaceCode = autoGeneratePrefix;
        let apiOptions: ApiOption[] = []; // 存放当前service全部api的一些信息
        // 拉取service信息
        try {
            const serviceRes = await GetServiceByUuidAndVersion(
                service_uuid,
                version
            );
            if (serviceRes.status !== 200) {
                console.warn(
                    `Failed to get service info for service ${name}: ${serviceRes.message}`
                );
                continue;
            }
            const apis =
                "apis" in serviceRes.service
                    ? serviceRes.service.apis
                    : "api_drafts" in serviceRes.service
                      ? serviceRes.service.api_drafts || []
                      : [];
            const isLatest = serviceRes.is_latest;
            console.log(
                `Service ${name} has ${apis.length} api${apis.length === 1 ? "" : "s"}`
            );

            // 获取api的参数信息
            for (const api of apis) {
                const apiRes = await GetApiById(api.id, isLatest);
                if (apiRes.status !== 200) {
                    console.warn(
                        `Failed to get api info for api ${api.name} in service ${name}: ${apiRes.message}`
                    );
                    continue;
                }
                const apiDetail = apiRes.api as ApiDetail | ApiDraftDetail;

                // 生成当前api的namespace代码
                const { namespaceCodeForThisApi, apiOption } =
                    await generateNamespaceCodeByApiDetail(apiDetail);
                namespaceCode += `\n\n${namespaceCodeForThisApi}`;
                apiOptions.push(apiOption);
            }
        } catch (error) {
            console.error(
                `Failed to get service info for service ${name}: ${error}`
            );
            continue;
        }

        // 统一生成namespaces.ts
        fs.writeFileSync(
            path.join(outputDir, "namespaces.ts"),
            await formatCodeByPrettier(namespaceCode)
        );
        // 统一生成index.ts
        const code = await formatCodeByPrettier(
            `${autoGeneratePrefix}\n${serviceClassCode(name, apiOptions)}`
        );
        fs.writeFileSync(path.join(outputDir, "index.ts"), code);
    }

    // 生成request-demo.ts（已格式化）
    const demoServiceName = Object.keys(config.services)[0];
    if (!demoServiceName) {
        process.exit(1);
    }
    const code = await formatCodeByPrettier(requestDemoCode(demoServiceName));
    fs.writeFileSync(path.join(outDir || ".", "request-demo.ts"), code);

    console.log(`All services' apis have been generated in ${outDir || "."}.`);
};

const generateNamespaceCodeByApiDetail = async (
    api: ApiDetail | ApiDraftDetail
): Promise<{ namespaceCodeForThisApi: string; apiOption: ApiOption }> => {
    const { namespaces, apiOption } = generateTSCode(api);
    const namespaceCodeForThisApi = namespaces.join("\n\n");

    return { namespaceCodeForThisApi, apiOption };
};
